name: chart-python pipeline
trigger:
  branches:
    include:
      - refs/tags/*
pr:
  branches:
    include:
      - main
resources:
  repositories:
    - repository: cnp-azuredevops-libraries
      type: github
      ref: refs/heads/master
      name: hmcts/cnp-azuredevops-libraries
      endpoint: "hmcts"

variables:
  - name: agentPool
    value: ubuntu-latest

jobs:
  - job: Validate
    pool:
      vmImage: ${{ variables.agentPool }}
    steps:
      - template: steps/charts/validate.yaml@cnp-azuredevops-libraries
        parameters:
          chartName: python
          chartReleaseName: chart-python-ci-test
          chartNamespace: chart-tests
          helmInstallTimeout: "500"

  - job: Release
    condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')
    pool:
      vmImage: ${{ variables.agentPool }}
    steps:
      - template: steps/charts/release.yaml@cnp-azuredevops-libraries
        parameters:
          chartName: python
          chartReleaseName: chart-python
          chartNamespace: chart-tests
